<div class="gd_footer" >
	<div class="gd_footer_title">
	 Contact information
	</div>
	<div class="gd_contact_info">  
		Tel: <?=$block->getPhoneNumber();?>
	</div>
	<div class="gd_contact_info">  
		Email: cs@gardendecorsdepot.com
		
	</div>
	<div id="store_address_1" class ="gd_office">
		<div class="gd_office_title">  
		Corporate/Billing office
		</div>
		<div class="gd_contact_info">  
			Open hours：Mon-Fri 8:00 to 16:30
		</div>
		<div class="gd_contact_info">  
		4010 Georgia Blvd,San Bernardino, CA 92407
		</div>
		<div class="gd_contact_info">  
		Tel:626-638-2378
		</div>
	</div>	
	<div id="store_address_2" class ="gd_office">
		
		<div class="gd_office_title">  
			Distribution Center
		</div>
		<div class="gd_contact_info">  
			Open hours：Mon-Fri 8:30 to 17:00
		</div>
		<div class="gd_contact_info">  
			6511 N Wayside Dr, Houston, TX, 77028 
		
		</div>
		<div class="gd_contact_info">  
		Tel:713-371-8447
		</div>
	</div>
	<div id="store_address_3" class ="gd_office">
		<div class="gd_office_title">  
		Distribution Center
		</div>
		<div class="gd_contact_info">  
			Open hours：Mon-Fri 8:00 to 16:30
		</div>
		<div class="gd_contact_info">  
		550 River Rd, Rio Vista, CA 94571
		
		</div>
		<div class="gd_contact_info">  
		Tel:626-638-2378
		</div>
	</div>

	<div id="store_address_4" class ="gd_office">
		<div class="gd_office_title">  
		Distribution Center
		</div>
		<div class="gd_contact_info">  
			Open hours：Mon-Fri 8:00 to 16:30
		</div>
		<div class="gd_contact_info">  
		1753 BLAKE AVE, LOS ANGELES, CA 90031
		
		</div>
		<div class="gd_contact_info">  
		Tel:323-605-7174
		</div>
	</div>
	<div id="store_address_5" class ="gd_office">
		<div class="gd_office_title">  
		Distribution Center (Coming soon)
		</div>
		<div class="gd_contact_info">  
			Open hours：Mon-Fri 8:00 to 16:30
		</div>
		<div class="gd_contact_info">  
		5375 Industrial Dr, Huntington Beach, CA 92649
		
		</div>
		<div class="gd_contact_info">  
		Tel:949-324-4563
		</div>
	</div>

</div>