<?php



?>



<div class="gd_homepage_video_wrapper"> 
	<div class="gd_youtube_video" onclick="alert('Video will be available soon!')"><p>Vinyl Fence Installation guide on youtube</p>
	<!---
		<iframe src="https://www.youtube.com/embed/7JiCy4UzveI?rel=0&amp;showinfo=0" width="100%" height="410" frameborder="0">
		</iframe>
	-->
	<img   src=<?php echo $block->getViewFileUrl('images/vinyl_install_novideo.jpg'); ?> alt="Video will be available soon" 
	width="%100" height="410" > 
	</div>
	<div class="gd_youtube_video"><p>Retractable canopy Installation guide on youtube</p>
		<iframe src="https://www.youtube.com/embed/8Y4X1xGx2r8" title="YouTube video player"  width="100%" height="410" frameborder="0">
		</iframe>
	</div>
	<div class="gd_youtube_video"><p>Roller shade Installation guide on youtube</p>
		<iframe src="https://www.youtube.com/embed/o6PQPvQ5gs4" title="YouTube video player"  width="100%" height="410" frameborder="0">
		</iframe>
	</div>
	
</div>