<?php



?>




<div class="gd_homepage_bundle_wrapper"> 

	<div class ="gd_homepage_bundle_title">   New Arrivals <br> In stock by July 2023
	</div>
	<div class="gd_homepage_bundle_categories">
	    <div  class="gd_homepage_bundle_category">
		<a class="gd_homepage_bundle_category_link" href = "#"> 

			<?php //xdebug_var_dump($productItem); break;?>

			<div class="gd_homepage_bundle_category_cat">
				<img class ="gd_homepage_bundle_category_image" src="amz_img/t/img/rib_a.jpg" alt ="" >

			</div>
			<div class="gd_homepage_bundle_category_description"> Ornmental Steel Feece <br> RIB(A) 94" Welded Residential Flat Top and Flat Bottom

			</div>
		</a>
		</div>
		<div  class="gd_homepage_bundle_category">
		<a class="gd_homepage_bundle_category_link" href = "#"> 

			<?php //xdebug_var_dump($productItem); break;?>

			<div class="gd_homepage_bundle_category_cat">
				<img class ="gd_homepage_bundle_category_image" src="amz_img/t/img/picket_a.jpg" alt ="" >

			</div>
			<div class="gd_homepage_bundle_category_description"> Ornmental Steel Feece <br>Picket(A) 94" Welded Residential Ext Top and Ext Flat Bottom - BIASABLE

			</div>
		</a>
		
		</div>	
		<div  class="gd_homepage_bundle_category">
		<a class="gd_homepage_bundle_category_link" href = "#"> 

			<?php //xdebug_var_dump($productItem); break;?>

			<div class="gd_homepage_bundle_category_cat">
				<img class ="gd_homepage_bundle_category_image" src="amz_img/t/img/picket_a_spear.jpg" alt ="" >

			</div>
			<div class="gd_homepage_bundle_category_description">Ornmental Steel Feece <br>Picket(A) 94" Welded Residential Spear Ext Top and Ext Flat Bottom - BIASABLE

			</div>
		</a>
		</div>	
	</div>
	
</div>