<?php
$ids = [36,19,20];


$catgoryCollection = $block->getCategyCollectionByParentIds($ids);
//$productCollection = $block->getProductCollectionByCategories($catgoryCollection);



?>

<div class="gd_homepage_bundle_wrapper"> 
	<div class ="gd_homepage_bundle_title">   Shopping Featured Product
	</div>
<?php
foreach($catgoryCollection as $subcat)
{
	
    $loop_count = 0;
	$categoryids =[];
	$categoryids[] = $subcat->getId();
	
	$productCollection = $block->getProductCollectionByCategories($categoryids);
	?>
	<div class ="gd_homepage_category_title"> <?php echo $subcat->getName();  ?> <hr></div>
    <?php foreach($productCollection as $productItem){ ?>
	
	<?php $customType = $block->getAttributeName($productItem, "gd_custom_type");
		  if ($customType == "stainless fence")
			  continue;
	?> 	
	<?php if ($loop_count%4 == 0): ?>
	    <div class="gd_homepage_bundle_categories">
	<?php endif; ?> 
	        <div  class="gd_homepage_bundle_category">
			<a class="gd_homepage_bundle_category_link" href = "<?php echo $productItem->getProductUrl();?>"> 
				<?php //xdebug_var_dump($productItem); break;?>
				<div class="gd_homepage_bundle_category_cat">
				<?php 
					
					//xdebug_var_dump($category->getDescription());
					//break;
					$loop_count++;
				?>
					<img class ="gd_homepage_bundle_category_image" src="<?php echo $block->getProductImgUrl($productItem);?>" alt ="sorry" >
				</div>
				<div class="gd_homepage_bundle_category_description"><?php echo $productItem->getName();?> 
				</div>
			</a>
				<div class="gd_homepage_shop_text">
				<a href= "<?php echo $productItem->getProductUrl();?>">
				
				<div class="gd_shop_text" id="gd_home_show_now" style="display:inline-block;"> <p>Shop Now</p>
				</div> 
				</a>
				</div>
			
			</div>
	<?php if ($loop_count%4 == 0): ?>
	       </div>
	<?php endif; ?>
	<?php } ?>
	<?php if ($loop_count%4 != 0): ?>
		</div>
	<?php endif; ?>
<?php } ?>
	
</div>